In [74]:
! pip install pandas

Requirement already satisfied: pandas in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/v0idgy/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [75]:
import pandas as pd

In [76]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago'],
    'Position': ['winner', 'first_runner_up', 'second_runner_up']
}
data

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': [25, 30, 35],
 'City': ['New York', 'Los Angeles', 'Chicago'],
 'Position': ['winner', 'first_runner_up', 'second_runner_up']}

In [77]:
df = pd.DataFrame(data)
df

      Name  Age         City          Position
0    Alice   25     New York            winner
1      Bob   30  Los Angeles   first_runner_up
2  Charlie   35      Chicago  second_runner_up

In [78]:
df[['Name','Age']] ## selecting multiple columns from the dataframe

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [79]:
df

      Name  Age         City          Position
0    Alice   25     New York            winner
1      Bob   30  Los Angeles   first_runner_up
2  Charlie   35      Chicago  second_runner_up

In [80]:
df.loc[1] ## selecting a single row from the dataframe using loc

Name                    Bob
Age                      30
City            Los Angeles
Position    first_runner_up
Name: 1, dtype: object

In [81]:
df.iloc[1] ## selecting a single row from the dataframe using iloc, it will select the second row of the dataframe because iloc uses integer indexing, so it starts from 0

Name                    Bob
Age                      30
City            Los Angeles
Position    first_runner_up
Name: 1, dtype: object

In [82]:
df

      Name  Age         City          Position
0    Alice   25     New York            winner
1      Bob   30  Los Angeles   first_runner_up
2  Charlie   35      Chicago  second_runner_up

## Setting individual column as a index

In [83]:
df.set_index('Position', inplace=True) ## setting the index of the dataframe to the 'Position' column, inplace=True will modify the original dataframe

Setting new data as index

In [84]:
df

                     Name  Age         City
Position
winner              Alice   25     New York
first_runner_up       Bob   30  Los Angeles
second_runner_up  Charlie   35      Chicago

In [85]:
df.index = ['winner','first_runner_up','second_runner_up'] ## setting the index of the dataframe to a list of values, it will replace the existing index with the new index

In [86]:
df

                     Name  Age         City
winner              Alice   25     New York
first_runner_up       Bob   30  Los Angeles
second_runner_up  Charlie   35      Chicago

In [87]:
df.iloc[1]  ## Position          ## selecting a single row from the dataframe using iloc, it will select the second row of the dataframe because iloc uses integer indexing, so it starts from 0

Name            Bob
Age              30
City    Los Angeles
Name: first_runner_up, dtype: object

In [88]:
df.loc['first_runner_up'] ## labels

Name            Bob
Age              30
City    Los Angeles
Name: first_runner_up, dtype: object

In [89]:
del df['City']

In [90]:
df

                     Name  Age
winner              Alice   25
first_runner_up       Bob   30
second_runner_up  Charlie   35

In [ ]:
df.drop(['Age'], axis=1) ## dropping a column from the dataframe, axis=1 means we are dropping a column, inplace=True will modify the original dataframe

                     Name
winner              Alice
first_runner_up       Bob
second_runner_up  Charlie

In [94]:
df

                     Name  Age
winner              Alice   25
first_runner_up       Bob   30
second_runner_up  Charlie   35

In [95]:
new_column = {
    'Name':'NAME',
    'Age':'AGE'
}
df.rename(columns=new_column, inplace=True) ## renaming columns in the dataframe, inplace=True will modify the original dataframe

df

                     NAME  AGE
winner              Alice   25
first_runner_up       Bob   30
second_runner_up  Charlie   35

In [108]:
df['NAME_UPPER'] = df['NAME'].str.upper() ## converting the values in the 'NAME' column to uppercase using the str.upper() method

In [107]:
df

                     NAME  AGE NAME_UPPER
winner              Alice   25      ALICE
first_runner_up       Bob   30        BOB
second_runner_up  Charlie   35    CHARLIE

## Performing Data Analysis Over Some Random Data

CSV Datafile

In [ ]:
data = pd.read_csv('data.csv') ## reading a csv file into a dataframe using the read_csv() method
data

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   NaN      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

In [ ]:
data.info() ## Descriptive statistics of the dataframe, it will show the number of non-null values, data types and memory usage of the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      str
 1   Age       4 non-null      float64
 2   City      5 non-null      str
 3   Position  5 non-null      str
dtypes: float64(1), str(3)
memory usage: 396.0 bytes

In [ ]:
data.describe() ## Statistical summary of the dataframe, it will show the count, mean, std, min, 25%, 50%, 75% and max values of the numerical columns in the dataframe

             Age
count   4.000000
mean   28.750000
std     2.986079
min    25.000000
25%    27.250000
50%    29.000000
75%    30.500000
max    32.000000

In [141]:
data.head(2)

    Name   Age         City   Position
0  Alice  30.0     New York    Manager
1    Bob  25.0  Los Angeles  Developer

In [142]:
data.tail(2)

    Name   Age     City    Position
3  David  28.0  Houston    Designer
4    Eve  32.0  Phoenix  Consultant

In [132]:
data.isnull().sum() ## checking for null values in the dataframe, it will return a dataframe of the same shape with boolean values indicating whether the value is null or not

Name        0
Age         1
City        0
Position    0
dtype: int64

In [122]:
data.notnull().sum() ## checking for non-null values in the dataframe, it will return a dataframe of the same shape with boolean values indicating whether the value is not null or not

Name        5
Age         4
City        5
Position    5
dtype: int64

Dropping the rows which has null values

In [ ]:
data.dropna() ## dropping rows with null values from the dataframe, it will return a new dataframe with the rows containing null values removed

    Name   Age         City    Position
0  Alice  30.0     New York     Manager
1    Bob  25.0  Los Angeles   Developer
3  David  28.0      Houston    Designer
4    Eve  32.0      Phoenix  Consultant

Dropping the columns which has null values

In [133]:
data.dropna(axis=1)

      Name         City    Position
0    Alice     New York     Manager
1      Bob  Los Angeles   Developer
2  Charlie      Chicago     Analyst
3    David      Houston    Designer
4      Eve      Phoenix  Consultant

In [123]:
data

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   NaN      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

Instead of dropping just fill the Null Values with actual values

In [ ]:
data.fillna(0, inplace=True) ## filling the null values in the dataframe with 0, inplace=True will modify the original dataframe

      Name   Age         City    Position
0    Alice  30.0     New York     Manager
1      Bob  25.0  Los Angeles   Developer
2  Charlie   0.0      Chicago     Analyst
3    David  28.0      Houston    Designer
4      Eve  32.0      Phoenix  Consultant

In [ ]:
data.fillna(data['Age'].mean(), inplace=True) ## filling the null values in the 'Age' column with the mean of the 'Age' column, inplace=True will modify the original dataframe
data

      Name    Age         City    Position
0    Alice  30.00     New York     Manager
1      Bob  25.00  Los Angeles   Developer
2  Charlie  28.75      Chicago     Analyst
3    David  28.00      Houston    Designer
4      Eve  32.00      Phoenix  Consultant